/* This file is automatically generated from src/include/gurt/errno_template.h.
 * DO NOT EDIT
 * To regenerate, run scons --gen-headers.
 *
 * Copyright (C) 2019 Intel Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted for any purpose (including commercial purposes)
 * provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions, and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions, and the following disclaimer in the
 *    documentation and/or materials provided with the distribution.
 *
 * 3. In addition, redistributions of modified forms of the source or binary
 *    code must carry prominent notices stating that the original code was
 *    changed and the date of the change.
 *
 *  4. All publications or advertising materials mentioning features or use of
 *     this software are asked, but not required, to acknowledge that it was
 *     developed by Intel Corporation and credit the contributors.
 *
 * 5. Neither the name of Intel Corporation, nor the name of any Contributor
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

typedef enum {
	DER_SUCCESS          = 0,
	DER_ERR_GURT_BASE    = (1000),
	DER_NO_PERM          = (DER_ERR_GURT_BASE + 1),
	DER_NO_HDL           = (DER_ERR_GURT_BASE + 2),
	DER_INVAL            = (DER_ERR_GURT_BASE + 3),
	DER_EXIST            = (DER_ERR_GURT_BASE + 4),
	DER_NONEXIST         = (DER_ERR_GURT_BASE + 5),
	DER_UNREACH          = (DER_ERR_GURT_BASE + 6),
	DER_NOSPACE          = (DER_ERR_GURT_BASE + 7),
	DER_ALREADY          = (DER_ERR_GURT_BASE + 8),
	DER_NOMEM            = (DER_ERR_GURT_BASE + 9),
	DER_NOSYS            = (DER_ERR_GURT_BASE + 10),
	DER_TIMEDOUT         = (DER_ERR_GURT_BASE + 11),
	DER_BUSY             = (DER_ERR_GURT_BASE + 12),
	DER_AGAIN            = (DER_ERR_GURT_BASE + 13),
	DER_PROTO            = (DER_ERR_GURT_BASE + 14),
	DER_UNINIT           = (DER_ERR_GURT_BASE + 15),
	DER_TRUNC            = (DER_ERR_GURT_BASE + 16),
	DER_OVERFLOW         = (DER_ERR_GURT_BASE + 17),
	DER_CANCELED         = (DER_ERR_GURT_BASE + 18),
	DER_OOG              = (DER_ERR_GURT_BASE + 19),
	DER_HG               = (DER_ERR_GURT_BASE + 20),
	DER_UNREG            = (DER_ERR_GURT_BASE + 21),
	DER_ADDRSTR_GEN      = (DER_ERR_GURT_BASE + 22),
	DER_PMIX             = (DER_ERR_GURT_BASE + 23),
	DER_IVCB_FORWARD     = (DER_ERR_GURT_BASE + 24),
	DER_MISC             = (DER_ERR_GURT_BASE + 25),
	DER_BADPATH          = (DER_ERR_GURT_BASE + 26),
	DER_NOTDIR           = (DER_ERR_GURT_BASE + 27),
	DER_CORPC_INCOMPLETE = (DER_ERR_GURT_BASE + 28),
	DER_NO_RAS_RANK      = (DER_ERR_GURT_BASE + 29),
	DER_NOTATTACH        = (DER_ERR_GURT_BASE + 30),
	DER_MISMATCH         = (DER_ERR_GURT_BASE + 31),
	DER_EVICTED          = (DER_ERR_GURT_BASE + 32),
	DER_NOREPLY          = (DER_ERR_GURT_BASE + 33),
	DER_DOS              = (DER_ERR_GURT_BASE + 34),
	DER_ERR_GURT_LIMIT,
	DER_ERR_DAOS_BASE = (2000),
	DER_IO            = (DER_ERR_DAOS_BASE + 1),
	DER_FREE_MEM      = (DER_ERR_DAOS_BASE + 2),
	DER_ENOENT        = (DER_ERR_DAOS_BASE + 3),
	DER_NOTYPE        = (DER_ERR_DAOS_BASE + 4),
	DER_NOSCHEMA      = (DER_ERR_DAOS_BASE + 5),
	DER_NOLOCAL       = (DER_ERR_DAOS_BASE + 6),
	DER_STALE         = (DER_ERR_DAOS_BASE + 7),
	DER_NOTLEADER     = (DER_ERR_DAOS_BASE + 8),
	DER_TGT_CREATE    = (DER_ERR_DAOS_BASE + 9),
	DER_EP_RO         = (DER_ERR_DAOS_BASE + 10),
	DER_EP_OLD        = (DER_ERR_DAOS_BASE + 11),
	DER_KEY2BIG       = (DER_ERR_DAOS_BASE + 12),
	DER_REC2BIG       = (DER_ERR_DAOS_BASE + 13),
	DER_IO_INVAL      = (DER_ERR_DAOS_BASE + 14),
	DER_EQ_BUSY       = (DER_ERR_DAOS_BASE + 15),
	DER_DOMAIN        = (DER_ERR_DAOS_BASE + 16),
	DER_SHUTDOWN      = (DER_ERR_DAOS_BASE + 17),
	DER_INPROGRESS    = (DER_ERR_DAOS_BASE + 18),
	DER_NOTAPPLICABLE = (DER_ERR_DAOS_BASE + 19),
	DER_ERR_DAOS_LIMIT,
	DER_UNKNOWN = DER_ERR_GURT_BASE + 500000,
} d_errno_t;

const char *d_errstr(int rc);
