#
# Copyright 2018, Intel Corporation
#
# 'recipe' for Docker to build an image of Ubuntu-based
# environment for building the DAOS project.
#

# Pull base image
FROM ubuntu:18.04
MAINTAINER Johann Lombardi <johann.lombardi@intel.com>

# Build arguments can be set via -build-arg
# set NOBUILD to disable git clone & build
ARG NOBUILD
# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Update distribution
# It's better to put the apt-get update in the same "cache layer" as the
# apt-get install command so that the apt database is updated if/when the
# installed packages list below is updated

# Install basic tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git   \
                       gcc golang-go make cmake libtool-bin scons autoconf    \
                       libboost-dev uuid-dev libssl-dev libevent-dev          \
                       libltdl-dev librdmacm-dev libcmocka0 libcmocka-dev     \
                       libreadline6-dev curl doxygen pandoc flex patch nasm   \
                       yasm graphviz doxygen libibverbs-dev librdmacm-dev     \
                       libcunit1-dev libnuma-dev libaio-dev sg3-utils         \
                       libiscsi-dev python-dev mscgen ninja-build meson       \
                       pylint bash locales go-dep
# Phyl
RUN apt-get install -y python3 python-yaml python3-yaml pylint3
RUN apt-get install -y python-paramiko python3-paramiko
RUN apt-get install -y valgrind rsync
RUN apt-get install -y python-github
RUN apt-get install -y libyaml-dev
# Couldn't find libsafec-dev
# Couldn't find libipmctl-dev

RUN ln -s /usr/bin/cc /bin/cc

# hack the default shell to bash instead of dash
RUN rm /bin/sh && ln -s bash /bin/sh

RUN locale-gen en_US.UTF-8

# Dependencies

# Add DAOS user
ENV USER daos
ENV PASSWD daos
RUN useradd -u $UID -ms /bin/bash $USER
RUN echo "$USER:$PASSWD" | chpasswd

# Create directory for DAOS backend storage
RUN mkdir /mnt/daos
RUN chown daos.daos /mnt/daos

# Switch to new user
USER $USER
WORKDIR /home/$USER

# Fetch DAOS code
RUN if [ "x$NOBUILD" = "x" ] ; then git clone https://github.com/daos-stack/daos.git; fi
WORKDIR /home/$USER/daos

# Build DAOS & dependencies
RUN if [ "x$NOBUILD" = "x" ] ; then git submodule init && git submodule update; fi
RUN if [ "x$NOBUILD" = "x" ] ; then scons --build-deps=yes USE_INSTALLED=all install; fi

# Set environment variables
ENV PATH=/home/daos/daos/install/bin:$PATH
ENV LD_LIBRARY_PATH=/home/daos/daos/install/lib:/home/daos/daos/install/lib/daos_srv:$LD_LIBRARY_PATH
ENV CPATH=/home/daos/daos/install/include:$CPATH
ENV CRT_PHY_ADDR_STR="ofi+sockets"
ENV OFI_INTERFACE=eth0
