#
# Copyright 2018, Intel Corporation
#
# 'recipe' for Docker to build an image of centOS-based
# environment for building the DAOS project.
#

# Pull base image
FROM centos:7
MAINTAINER Johann Lombardi <johann.lombardi@intel.com>

# Build arguments can be set via -build-arg
# set NOBUILD to disable git clone & build
ARG NOBUILD
# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Update distribution
#Nothing to do for CentOS

# Install basic tools
RUN yum install -y epel-release
RUN yum install -y git gcc gcc-c++ make cmake golang libtool scons boost-devel   \
                   libuuid-devel openssl-devel libevent-devel libtool-ltdl-devel \
                   libcmocka libcmocka-devel readline-devel                      \
                   doxygen pandoc flex patch nasm yasm ninja-build meson         \
                   CUnit-devel libaio-devel python-pep8 lcov                     \
                   python clang-analyzer sg3_utils libiscsi-devel                \
                   numactl-devel doxygen graphviz pylint valgrind rsync
# these are needed for test_runner and can be removed when we are done using it
RUN yum install -y python34 python34-pylint python34-PyYAML.x86_64 PyYAML.x86_64 \
                   python2-paramiko python34-paramiko
RUN yum -y install ShellCheck
#RUN yum -y install python2-pygithub.noarch
# ugly hack for https://bugzilla.redhat.com/show_bug.cgi?id=1634082
RUN yumdownloader python2-pygithub && yum -y install python-jwt && rpm --nodeps -ivh python2-pygithub-*.el7.noarch.rpm
# ugly hack for https://github.com/PyGithub/PyGithub/pull/909 until we get a
# new release
RUN echo -e "From c53fe24fe8529dd2dd0a989a4a57b49ace2e1a6d Mon Sep 17 00:00:00 2001\n\
From: "Brian J. Murrell" <brian@interlinx.bc.ca>\n\
Date: Tue, 25 Sep 2018 17:31:10 -0400\n\
Subject: [PATCH] Line comments are not posted in create_review()\n\
\n\
When create_review() is called with comments in the comments argument,\n\
they are not actually posted in the API call.\n\
---\n\
 github/PullRequest.py | 2 ++\n\
 1 file changed, 2 insertions(+)\n\
\n\
diff --git a/github/PullRequest.py b/github/PullRequest.py\n\
index c855dfb8..688e0625 100644\n\
--- /usr/lib/python2.7/site-packages/github/PullRequest.py.old\n\
+++ /usr/lib/python2.7/site-packages/github/PullRequest.py\n\
@@ -434,6 +434,8 @@ def create_review(self, commit, body, event=github.GithubObject.NotSet, comments\n\
         post_parameters['event'] = 'COMMENT' if event == github.GithubObject.NotSet else event\n\
         if comments is github.GithubObject.NotSet:\n\
             post_parameters['comments'] = []\n\
+        else:\n\
+            post_parameters['comments'] = comments\n\
         headers, data = self._requester.requestJsonAndCheck(\n\
             "POST",\n\
             self.url + "/reviews",\n" | patch -p0

# Dependencies
# Packages for NVML, PMIx, hwloc and OpenMPI exist in CentOS, but are unfortunately
# outdated. The DAOS build system will rebuilt those packages.

# Phyl
# Get all the DAOS stuff out of here

# Add CaRT user
ENV USER cart
ENV PASSWD cart
RUN useradd -u $UID -ms /bin/bash $USER
RUN echo "$USER:$PASSWD" | chpasswd

# Phyl
# Create directory for DAOS backend storage
#RUN mkdir /mnt/daos
#RUN chown daos.daos /mnt/daos

# Switch to new user
USER $USER
WORKDIR /home/$USER

# Fetch CaRT code
RUN if [ "x$NOBUILD" = "x" ] ; then git clone https://github.com/daos-stack/cart.git; fi
WORKDIR /home/$USER/cart

# Build CaRT & dependencies
RUN if [ "x$NOBUILD" = "x" ] ; then git submodule init && git submodule update; fi
RUN if [ "x$NOBUILD" = "x" ] ; then scons --build-deps=yes USE_INSTALLED=all install; fi

# Set environment variables
ENV PATH=/home/cart/cart/install/bin:$PATH
ENV LD_LIBRARY_PATH=/home/cart/cart/install/lib:/home/cart/cart/install/lib/cart_srv:$LD_LIBRARY_PATH
ENV CPATH=/home/cart/cart/install/include:$CPATH
ENV CRT_PHY_ADDR_STR="ofi+sockets"
ENV OFI_INTERFACE=eth0
